server:
  port: ${SERVER_PORT:8084}
spring:
  application:
    name: notification-service

  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: smtp.gmail.com
    port: 587
    username: madeeasycodinglife@gmail.com
    password: jneb tpuf wtkd mtbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


resilience4j:
  circuitbreaker:
    configs:
      notificationServiceCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 20
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
    instances:
      myCircuitBreaker: # this name is used in the annotation
        baseConfig: notificationServiceCircuitBreaker
