server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: expense-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:expense-service}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  h2:
    console:
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      settings:
        web-allow-others: true

  web:
    resources:
      add-mappings: ${SPRING_WEB_RESOURCES_ADD_MAPPINGS:false}

  output:
    ansi:
      enabled: ALWAYS


security:
  authorization:
    paths:
      - path: /approval-service/ask-for-approve
        method: POST
        roles: ${SECURITY_AUTHORIZATION_PATHS_SIGNUP_ROLES:EMPLOYEE}
      - path: /approval-service/approve
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_SIGNUP_ROLES:MANAGER,FINANCE,ADMIN}