server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: expense-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:expense-service}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  h2:
    console:
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      settings:
        web-allow-others: true

  web:
    resources:
      add-mappings: ${SPRING_WEB_RESOURCES_ADD_MAPPINGS:false}

  output:
    ansi:
      enabled: ALWAYS


resilience4j:
  circuitbreaker:
    configs:
      expenseServiceCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 20
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
    instances:
      myCircuitBreaker: # this name is used in the annotation
        baseConfig: expenseServiceCircuitBreaker


security:
  authorization:
    paths:
      - path: /expense-service/**
        method: GET, POST, PATCH, DELETE
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
