server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: expense-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:expense-service}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  h2:
    console:
      path: ${SPRING_H2_CONSOLE_PATH:/h2-console}
      enabled: ${SPRING_H2_CONSOLE_ENABLED:true}
      settings:
        web-allow-others: true

  web:
    resources:
      add-mappings: ${SPRING_WEB_RESOURCES_ADD_MAPPINGS:false}

  output:
    ansi:
      enabled: ALWAYS


resilience4j:
  circuitbreaker:
    configs:
      expenseServiceCircuitBreaker:
        registerHealthIndicator: true
        failureRateThreshold: 20
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
    instances:
      myCircuitBreaker: # this name is used in the annotation
        baseConfig: expenseServiceCircuitBreaker


security:
  authorization:
    paths:

#      - path: /expense-service/**
#        method: GET, POST, PATCH, DELETE
#        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}

      - path: /expense-service/v3/api-docs
        method: GET, POST, PATCH, DELETE
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:}

      - path: /expense-service/get/{id}
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/get-all-expenses
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/submit
        method: POST
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/delete/**
        method: DELETE
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/update/**
        method: PATCH
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/category/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/generate/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/expenses/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/expenses/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/expenses/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE}
      - path: /expense-service/monthly-trends/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE,ADMIN,FINANCE,MANAGER}

      - path: /expense-service/yearly-trends/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE,ADMIN,FINANCE,MANAGER}

      - path: /expense-service/category-breakdown/**
        method: GET
        roles: ${SECURITY_AUTHORIZATION_PATHS_ROLES:EMPLOYEE,ADMIN,FINANCE,MANAGER}


eureka:
  client:
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRY_FETCH_INTERVAL_SECONDS:30}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}  # Add the hostname property here
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    lease-renewal-interval-in-seconds: ${EUREKA_INSTANCE_LEASE_RENEWAL_INTERVAL_IN_SECONDS:10}
    lease-expiration-duration-in-seconds: ${EUREKA_INSTANCE_LEASE_EXPIRATION_DURATION_IN_SECONDS:90}


management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}
  health:
    circuitbreakers:
      enabled: ${MANAGEMENT_HEALTH_CIRCUITBREAKERS_ENABLED:true}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:ALWAYS}
  tracing:
    enabled: ${MANAGEMENT_TRACING_ENABLED:true}
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}


springdoc:
  api-docs:
    groups:
      enabled: true
    path: /expense-service/v3/api-docs
  swagger-ui:
    enabled: false
